image: archlinux
packages:
  - cargo-audit
  - cargo-udeps
  - cargo-spellcheck
  - rust
sources:
  - https://git.sr.ht/~danyspin97/rinstall
environment:
  pkg: rinstall
tasks:
  - build: |
      cd "$pkg"
      cargo build
  - test: |
      cd "$pkg"
      cargo test
  - check-format: |
      cd "$pkg"
      cargo fmt -- --check
  - audit: |
      cd "$pkg"
      cargo audit
  # Cargo deps require Rust nightly as of version 1.54.0
  #- check-unused-deps: |
  #    cd "$pkg"
  #    res=$(cargo udeps)
  #    if [[ "$res" != "All dependencies are up to date, yay!" ]];
  #        echo $res
  #        exit 1
  #    fi
  - spellcheck: |
      cd "$pkg"
      cargo spellcheck --code=1
