[package]
name = "rinstall"
version = "0.1.0"
edition = "2018"

[dependencies]
blake3 = "1.3.1"
clap = { version = "3.1.1", features = ["derive"] }
color-eyre = "0.6.0"
colored = "2.0.0"
json = "0.12.4"
lazy_static = "1.4.0"
libc = "0.2.119"
semver = { version = "1.0.5", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
xdg = "2.4.0"
walkdir = "2.3.2"
void = "1.0.2"
