[package]
name = "rinstall"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0+"
authors = ["Danilo Spinella <danilo.spinella@suse.com>"]
keywords = ["packaging"]
repository = "https://github.com/danyspin97/rinstall"
homepage = "https://github.com/danyspin97/rinstall"
description = "Declarative install for programs"
categories = ["command-line-utilities"]

[dependencies]
blake3 = "1.3.1"
camino = { version = "1.0.7", features = [ "serde1" ] }
clap = { version = "3.1.6", features = ["derive", "env", "wrap_help"] }
color-eyre = { version = "0.6.1", default_features = false }
colored = "2.0.0"
json = "0.12.4"
lazy_static = "1.4.0"
libc = "0.2.121"
semver = { version = "1.0.7", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
xdg = "2.4.1"
walkdir = "2.3.2"
void = "1.0.2"

[build-dependencies]
clap = { version = "3.1.6", features = ["derive", "cargo", "env"] }
clap_complete = "3.1.1"
clap_mangen = "0.1.2"
# used for the imports in src/config.rs
serde = { version = "1.0.136", features = ["derive"] }
