[package]
name = "rinstall"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
color-eyre = "0.5"
json = "0.12"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
xdg = "2.1"
walkdir = "2"
