on:
  push:
    tags:
      - '*.*.*'

name: Release

jobs:
  release:
    name: Release Packaging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:  [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Release Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Strip binary
        run: strip target/${{ matrix.target }}/release/rinstall
      - name: Create tarball
        run: |
            touch .tarball
            tar -cvf rinstall-${{ matrix.target }}.tar.zst \
                target/${{ matrix.target }}/release/rinstall \
                README.md \
                LICENSE.md \
                install.yml \
                .tarball
      - name: Upload release tarball
        uses: softprops/action-gh-release@v1
        with:
          files: rinstall-${{ matrix.target }}.tar.zst
